[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-uland"
version = "250406"
description = "A light 2D land system plug-in with rich and interesting features."

[project.entry-points."endstone"]
uland = "endstone_uland:uland"