import os
import json

class lang():
    def load_lang(self, lang_dir: str) -> dict:
        zh_CN_data_file_path = os.path.join(lang_dir, 'zh_CN.json')
        en_US_data_file_path = os.path.join(lang_dir, 'en_US.json')

        if not os.path.exists(zh_CN_data_file_path):
            with open(zh_CN_data_file_path, 'w', encoding='utf-8') as f:
                zh_CN = {
                    'coordinates': '坐标',
                    'dimension': '维度',
                    'land_buy_expense': '领地价格',
                    'land_sell_expense': '领地回收价格',
                    'land_name': '领地名',
                    'player_money': '你的余额',
                    'point_a': 'A点',
                    'point_b': 'B点',
                    'area': '面积',
                    'range': '范围',
                    'default_new_land_name': "{0}的领地",
                    'owner': '领主',
                    'member': '成员',
                    'members': '成员',
                    'none': '无',
                    'teleport_point': '传送点',
                    'creation_time': '创建时间',
                    'button.back': '返回上一级',
                    'message.type_error': '表单解析错误, 请按提示正确填写...',

                    'main_form.title': 'ULand - 主表单',
                    'main_form.content': '请选择操作...',
                    'main_form.button.create_new_land': '开始圈地',
                    'main_form.button.my_land': '我的领地',
                    'main_form.button.land_info': '查询脚下领地',
                    'main_form.button.public_land': '服务器公开领地',
                    'main_form.button.land_manage': '管理所有领地',
                    'main_form.button.reload_config': '重载配置文件',
                    'main_form.button.close': '关闭',
                    'main_form.button.back_to_zx_ui': '返回',

                    'create_land.message_1': '圈地模式已开启, 请在 {0}s 内完成圈地...',
                    'create_land.message_2': '输入 /posa 选中A点',
                    'create_land.message_3': '输入 /posb 选中B点',
                    'create_land.message_4': '注意： 不能跨维度选点, 所选A点坐标和B点坐标不能重复！',
                    'create_land.message.fail_1': '你没有正在进行的圈地进程...',
                    'create_land.message.fail_2': '圈地失败',
                    'create_land.message.fail_2.reason_1': '你所拥有的领地已达上限...',
                    'create_land.message.fail_2.reason_2': '你当前没有正在进行的圈地进程...',
                    'create_land.message.fail_2.reason_3': '你圈中的领地和一个已经存在的领地重叠, 相关数据已清空...',
                    'create_land.message.fail_2.reason_4': '你圈中的领地的面积太小了, 相关数据已清空...',
                    'create_land.message.fail_2.reason_5': '你圈中的领地的面积大于 {0}, 相关数据已清空...',
                    'create_land.message.fail_2.reason_6': '你的余额不足以支付圈中领地的价格',
                    'create_land.message.fail_2.reason_7': '你已经有一个名为 {0} 的领地了, 相关数据已清空...',
                    'create_land.message.fail_3': '圈地超时',
                    'create_land.message.fail_4': '相关数据已清空...',
                    'create_land.message.fail_5': '选点失败',
                    'create_land.message.fail_5.reason_1': '你还没有选中A点...',
                    'create_land.message.fail_5.reason_2': '你不能跨纬度选点...',
                    'create_land.message.fail_5.reason_3': '你不能选中和A点重复的点...',
                    'create_land.message.success_1': '选中A点成功',
                    'create_land.message.success_2': '更新A点成功',
                    'create_land.message.success_3': '选中B点成功',
                    'create_land.message.success_4': '圈地成功...',
                    'create_land.message.cancel': '圈地取消',
                    'create_land.from.title': "圈地表单",
                    'create_land.from.textinput.label_1': "输入领地名称",
                    'create_land.from.textinput.label_2': "留空默认领地名为： {0}的领地",
                    'create_land.from.textinput.placeholder': '请输入任意字符串或留空...',

                    'my_land_form.title': '我的领地',
                    'my_land_form.content': '请选择操作...',

                    'my_land_detail_form.content': '请选择操作...',
                    'my_land_detail_form.button.tp': '传送领地',
                    'my_land_detail_form.button.settings': '设置领地',
                    'land_tp.message.success': '传送成功, 欢迎回家...',

                    'my_land_setting_form.title': '设置领地',
                    'my_land_setting_form.content_1': '你正在对领地 {0} 进行操作',
                    'my_land_setting_form.content_2': '请选择操作...',
                    'my_land_setting_form.button.add_member': '添加领地成员',
                    'my_land_setting_form.button.delete_member': '删除领地成员',
                    'my_land_setting_form.button.land_rename': '重命名领地',
                    'my_land_setting_form.button.land_security_setting': '设置领地安全',
                    'my_land_setting_form.button.land_tp_setting': '设置领地传送点',
                    'my_land_setting_form.button.land_sell': '回收领地',
                    'my_land_setting_form.button.land_ownership_transfer': '转让领地',

                    'land_add_member_form.title': '添加领地成员',
                    'land_add_member_form.dropdown.label': '选择玩家',
                    'land_add_member_form.submit_button': '添加',
                    'land_add_member.message.fail': '添加领地成员失败',
                    'land_add_member.message.fail.reason': '当前没有可用于添加到领地成员的玩家...',
                    'land_add_member.message.success': '添加领地成员成功...',

                    'land_delete_member_form.title': '删除领地成员',
                    'land_delete_member_form.dropdown.label': '选择玩家',
                    'land_delete_member_form.submit_button': '删除',
                    'land_delete_member_form.message.fail': '删除领地成员失败',
                    'land_delete_member_form.message.fail.reason': '当前该领地没有任何成员...',
                    'land_delete_member_form.message.success': '删除领地成员成功...',

                    'land_rename_form.title': '重命名领地',
                    'land_rename_form.textinput.label': '输入新的领地名',
                    'land_rename_form.textinput.placeholder': '请输入任意字符串, 但不能留空...',
                    'land_rename_form.submit_button': '重命名',
                    'land_rename.message.fail': '重命名领地失败',
                    'land_rename.message.fail.reason': '你已经有一个名为 {0} 的领地了...',
                    'land_rename.message.success': '重命名领地成功...',

                    'land_security_setting_form.title': '设置领地安全',
                    'land_security_setting_form.toggle_1.label': '开启领地防火',
                    'land_security_setting_form.toggle_2.label': '开启领地防爆',
                    'land_security_setting_form.toggle_3.label': '阻止凋零进入领地',
                    'land_security_setting_form.toggle_4.label': '阻止非领地成员右键交互方块',
                    'land_security_setting_form.toggle_5.label': '阻止非领地成员破坏方块',
                    'land_security_setting_form.toggle_6.label': '阻止非领地成员右键交互实体',
                    'land_security_setting_form.toggle_7.label': '阻止非领地成员攻击',
                    'land_security_setting_form.toggle_8.label': '公开领地传送点',
                    'land_security_setting_form.submit_button': '更新',
                    'land_security_setting.message.success': '更新领地安全设置成功...',

                    'land_teleport_point_setting_form.title': '设置领地传送点',
                    'land_teleport_point_setting_form.content': '领地传送点将被更新为',
                    'land_teleport_point_setting_form.button.confirm': '确认',
                    'land_teleport_point_setting.message.success': '更新领地传送点成功...',

                    'land_sell_form.title': '回收领地',
                    'land_sell_form.content_1': '你正在对领地 {0} 进行操作',
                    'land_sell_form.content_2': '领地回收价格浮动未开启',
                    'land_sell_form.content_3': '当日领地回收价率',
                    'land_sell_form.content_4': '领地回收价格浮动已开启',
                    'land_sell_form.content_5': '今天离你创建该领地已满 {0} 天',
                    'land_sell_form.content_6': '可回收',
                    'land_sell_form.content_7': '今天离你创建该领地未满 {0} 天',
                    'land_sell_form.content_8': '不可回收',
                    'land_sell_form.button.sell': '回收',
                    'land_sell.message.success': '回收领地成功...',

                    'land_ownership_transfer_form.title': '转让领地',
                    'land_ownership_transfer_form.dropdown.label': '选择玩家',
                    'land_ownership_transfer_form.submit_button': '转让',
                    'land_ownership_transfer.message.fail': '转让领地失败',
                    'land_ownership_transfer.message.fail.reason': '当前没有可用于转让领地的玩家...',
                    'land_ownership_transfer.message.success': '转让领地成功...',

                    'land_info_form.title': '脚下领地信息',
                    'land_info.message.fail': '查询领地失败',
                    'land_info.message.fail.reason': '你的脚下没有任何领地...',

                    'server_public_land_form.title': '服务器公开领地',
                    'server_public_land_form.content': '请选择操作...',
                    'server_public_land_form.button.tp': '传送领地',

                    'reload_config_form.title': '服务器公开领地',
                    'reload_config_form.content': '请选择操作...',
                    'reload_config_form.button.reload_global_config': '重载全局配置',
                    'reload_config_form.button.reload_land_data': '重载领地数据',

                    'reload_global_config_form.title': '重载全局配置',
                    'reload_global_config_form.textinput_1.label': '当前领地单价',
                    'reload_global_config_form.textinput_1.placeholder': '请输入一个正整数...',
                    'reload_global_config_form.textinput_2.label': '当前圈地最大耗时',
                    'reload_global_config_form.textinput_2.placeholder': '请输入一个不小于30的正整数...',
                    'reload_global_config_form.textinput_3.label': '当前允许的最大领地面积',
                    'reload_global_config_form.textinput_3.placeholder': '请输入一个不小于4的正整数...',
                    'reload_global_config_form.textinput_4.label': '当前允许玩家拥有的最大领地数量',
                    'reload_global_config_form.textinput_4.placeholder': '请输入一个正整数...',
                    'reload_global_config_form.toggle.label': '开启领地回收价格浮动',
                    'reload_global_config_form.textinput_5.label': '当前领地回收冷却时间',
                    'reload_global_config_form.textinput_5.placeholder': '请输入一个不小于1的正整数...',
                    'reload_global_config_form.submit_button': '重载',
                    'reload_global_config.message.success': '重载全局配置成功...',

                    'reload_land_data.message.success': '重载领地数据成功...',

                    'manage_land_form.title': '管理所有领地',
                    'manage_land_form.content': '你是管理员, 你可以管理服务器所有领地...',

                    'manage_land_detail_form.content': '请选择操作...',
                    'manage_land_detail_form.button.tp': '传送领地',
                    'manage_land_detail_form.button.land_delete': '删除领地',

                    'manage_land_delete_form.title': '删除领地',
                    'manage_land_delete_form.content': '你确定删除此领地吗？',
                    'manage_land_delete_form.button.confirm': '确认',
                    'manage_land_delete.message.success': '删除领地成功...',

                    'tip': '§e你现在位于 §f{1} §e的领地 §f{0}',
                    'message.on_block_break': '你无权在此领地破坏方块...',
                    'message.on_player_attack': '你无权在此领地攻击玩家或生物...',
                    'message.on_player_right_click_block': '你无权在此领地右键交互方块...',
                    'message.on_player_right_click_entity': '你无权在此领地右键交互实体...'
                }
                json_str = json.dumps(zh_CN, indent=4, ensure_ascii=False)
                f.write(json_str)

        if not os.path.exists(en_US_data_file_path):
            with open(en_US_data_file_path, 'w', encoding='utf-8') as f:
                en_US = {
                    'coordinates': 'Coordinates',
                    'dimension': 'Dimension',
                    'land_buy_expense': 'Land buy expense',
                    'land_sell_expense': 'Land sell expense',
                    'land_name': 'Land name',
                    'player_money': 'Your money',
                    'point_a': 'Point A',
                    'point_b': 'Point B',
                    'area': 'Area',
                    'range': 'Range',
                    'default_new_land_name': "{0}'s land",
                    'owner': 'Owner',
                    'member': 'Member',
                    'members': 'Members',
                    'none': 'None',
                    'teleport_point': 'Teleport point',
                    'creation_time': 'Creation time',
                    'button.back': 'Back to previous',
                    'message.type_error': 'The form is parsed incorrectly, please follow the prompts to fill in correctly...',

                    'main_form.title': 'ULand - main form',
                    'main_form.content': 'Please select a function...',
                    'main_form.button.create_new_land': 'Create a new land',
                    'main_form.button.my_land': 'My lands',
                    'main_form.button.land_info': 'Query the land under feet',
                    'main_form.button.public_land': 'Server public lands',
                    'main_form.button.land_manage': 'Manage all lands',
                    'main_form.button.reload_config': 'Reload configurations',
                    'main_form.button.close': 'close',
                    'main_form.button.back_to_zx_ui': 'Back to menu',

                    'create_land.message_1': 'Land create mode has been activated, please complete the land create within {0}s...',
                    'create_land.message_2': 'Enter /posa to select point A',
                    'create_land.message_3': 'Enter /posb to select point B',
                    'create_land.message_4': 'Warning: you cannot select points across dimensions, and the selected point A and point B cannot be the same!',
                    'create_land.message.fail_1': 'You do not have any ongoing land create task...',
                    'create_land.message.fail_2': 'Failed to create land',
                    'create_land.message.fail_2.reason_1': 'you have reached the max number of lands...',
                    'create_land.message.fail_2.reason_2': 'you have a ongoing land create task...',
                    'create_land.message.fail_2.reason_3': 'the land you want to create overlaps with an existing land, relevant data has been cleared...',
                    'create_land.message.fail_2.reason_4': 'the area of the land you want to create is too small, relevant data has been cleared...',
                    'create_land.message.fail_2.reason_5': 'the area of the land you want to create larger than {0}, relevant data has been cleared...',
                    'create_land.message.fail_2.reason_6': 'your money is not sufficient to pay for the land you want to create',
                    'create_land.message.fail_2.reason_7': 'you already have a land named {0}, relevant data has been cleared...',
                    'create_land.message.fail_3': 'Land create overtime',
                    'create_land.message.fail_4': 'relevant data has been cleared...',
                    'create_land.message.fail_5': 'Failed to select a point',
                    'create_land.message.fail_5.reason_1': 'you have not selected point A yet...',
                    'create_land.message.fail_5.reason_2': 'you cannot select a point across dimensions...',
                    'create_land.message.fail_5.reason_3': 'you cannot select a point that is the same as point A...',
                    'create_land.message.success_1': 'Successfully selected point A',
                    'create_land.message.success_2': 'Successfully updated point A',
                    'create_land.message.success_3': 'Successfully selected point B',
                    'create_land.message.success_4': 'Successfully create land...',
                    'create_land.message.cancel': 'Cancel the creation of land',
                    'create_land.from.title': "Create a new land",
                    'create_land.from.textinput.label_1': "Input the name of new land",
                    'create_land.from.textinput.label_2': "The land name will be {0}'s land if left blank",
                    'create_land.from.textinput.placeholder': 'Input any string or left blank...',

                    'my_land_form.title': 'My lands',
                    'my_land_form.content': 'Please select a function...',

                    'my_land_detail_form.content': 'Please select a function...',
                    'my_land_detail_form.button.tp': 'Land teleport',
                    'my_land_detail_form.button.settings': 'Land settings',
                    'land_tp.message.success': 'Successfully teleport, welcome home...',

                    'my_land_setting_form.title': 'Land settings',
                    'my_land_setting_form.content_1': 'You are operating on {0}',
                    'my_land_setting_form.content_2': 'Please select a function...',
                    'my_land_setting_form.button.add_member': 'Add a land member',
                    'my_land_setting_form.button.delete_member': 'Delete a land member',
                    'my_land_setting_form.button.land_rename': 'Land rename',
                    'my_land_setting_form.button.land_security_setting': 'Land security settings',
                    'my_land_setting_form.button.land_tp_setting': 'Land teleport point setting',
                    'my_land_setting_form.button.land_sell': 'Land sell',
                    'my_land_setting_form.button.land_ownership_transfer': 'Land ownership transfer',

                    'land_add_member_form.title': 'Add a land member',
                    'land_add_member_form.dropdown.label': 'Select a player',
                    'land_add_member_form.submit_button': 'Add',
                    'land_add_member.message.fail': 'Failed to add a land member',
                    'land_add_member.message.fail.reason': 'there are no players available for adding to the land members...',
                    'land_add_member.message.success': 'Successfully add a land member...',

                    'land_delete_member_form.title': 'Delete a land member',
                    'land_delete_member_form.dropdown.label': 'Select a player',
                    'land_delete_member_form.submit_button': 'Delete',
                    'land_delete_member.message.fail': 'Failed to delete a land member',
                    'land_delete_member.message.fail.reason': 'there are no members in this land...',
                    'land_delete_member.message.success': 'Successfully delete a land member...',

                    'land_rename_form.title': 'Land rename',
                    'land_rename_form.textinput.label': 'Input new name of this land',
                    'land_rename_form.textinput.placeholder': 'Input any string, but cannot be blank...',
                    'land_rename_form.submit_button': 'Rename',
                    'land_rename.message.fail': 'Failed to rename this land',
                    'land_rename.message.fail.reason': 'you already have a land named {0}...',
                    'land_rename.message.success': 'Successfully rename this land',

                    'land_security_setting_form.title': 'Land security settings',
                    'land_security_setting_form.toggle_1.label': 'Enable land fire protection',
                    'land_security_setting_form.toggle_2.label': 'Enable land explosion protection',
                    'land_security_setting_form.toggle_3.label': 'Prevent withers from entering land',
                    'land_security_setting_form.toggle_4.label': 'Prevent strangers from right-clicking on blocks',
                    'land_security_setting_form.toggle_5.label': 'Prevent strangers from breaking blocks',
                    'land_security_setting_form.toggle_6.label': 'Prevent strangers from right-clicking on entities',
                    'land_security_setting_form.toggle_7.label': 'Prevent strangers from attacking',
                    'land_security_setting_form.toggle_8.label': 'Make land teleport point public',
                    'land_security_setting_form.submit_button': 'Update',
                    'land_security_setting.message.success': 'Successfully update land security settings...',

                    'land_teleport_point_setting_form.title': 'Land teleport point setting',
                    'land_teleport_point_setting_form.content': 'Land teleport will be update to',
                    'land_teleport_point_setting_form.button.confirm': 'Confirm',
                    'land_teleport_point_setting.message.success': 'Successfully update land teleport point...',

                    'land_sell_form.title': 'Land sell',
                    'land_sell_form.content_1': 'You are operating on {0}',
                    'land_sell_form.content_2': 'The price fluctuation for land sell is disabled',
                    'land_sell_form.content_3': 'Current price rate of land sell',
                    'land_sell_form.content_4': 'The price fluctuation for land sell is enabled',
                    'land_sell_form.content_5': 'It has been {0} days since you created this land today',
                    'land_sell_form.content_6': 'Available for land sell',
                    'land_sell_form.content_7': 'It has been less than {0} day(s) since you created this land today',
                    'land_sell_form.content_8': 'Not available for land sell',
                    'land_sell_form.button.sell': 'Sell',
                    'land_sell.message.success': 'Successfully to sell this land...',

                    'land_ownership_transfer_form.title': 'Land ownership transfer',
                    'land_ownership_transfer_form.dropdown.label': 'Select a player',
                    'land_ownership_transfer_form.submit_button': 'Transfer',
                    'land_ownership_transfer.message.fail': 'Failed to transfer ownership',
                    'land_ownership_transfer.message.fail.reason': 'there are no players available for land ownership transfer...',
                    'land_ownership_transfer.message.success': 'Successfully transfer ownership...',

                    'land_info_form.title': 'Land info under feet',
                    'land_info.message.fail': 'Failed to query',
                    'land_info.message.fail.reason': 'there is no land under your feet...',

                    'server_public_land_form.title': 'Server public lands',
                    'server_public_land_form.content': 'Please select a function...',
                    'server_public_land_form.button.tp': 'Land teleport',

                    'reload_config_form.title': 'Server public lands',
                    'reload_config_form.content': 'Please select a function...',
                    'reload_config_form.button.reload_global_config': 'Reload global configurations',
                    'reload_config_form.button.reload_land_data': 'Reload land data',

                    'reload_global_config_form.title': 'Reload global configurations',
                    'reload_global_config_form.textinput_1.label': 'The current land price in single square',
                    'reload_global_config_form.textinput_1.placeholder': 'Input a positive integer...',
                    'reload_global_config_form.textinput_2.label': 'The current valid time of land create task in seconds',
                    'reload_global_config_form.textinput_2.placeholder': 'Input a integer not less than 30...',
                    'reload_global_config_form.textinput_3.label': 'The current max area that single land is permitted',
                    'reload_global_config_form.textinput_3.placeholder': 'Input a integer not less than 4...',
                    'reload_global_config_form.textinput_4.label': 'The current max number of lands that players are allowed to have',
                    'reload_global_config_form.textinput_4.placeholder': 'Input a positive integer...',
                    'reload_global_config_form.toggle.label': 'Enable price fluctuation of land sell',
                    'reload_global_config_form.textinput_5.label': 'The current cooldown time in days of land sell',
                    'reload_global_config_form.textinput_5.placeholder': 'Input a integer not less than 1...',
                    'reload_global_config_form.submit_button': 'Reload',
                    'reload_global_config.message.success': 'Successfully reload global configurations...',

                    'reload_land_data.message.success': 'Successfully reload land data...',

                    'manage_land_form.title': 'Manage all lands',
                    'manage_land_form.content': 'You are a operator, you can manage all lands of the server...',

                    'manage_land_detail_form.content': 'Please select a function...',
                    'manage_land_detail_form.button.tp': 'Land teleport',
                    'manage_land_detail_form.button.land_delete': 'Land delete',

                    'manage_land_delete_form.title': 'Land delete',
                    'manage_land_delete_form.content': 'Are you sure to delete this land?',
                    'manage_land_delete_form.button.confirm': 'Confirm',
                    'manage_land_delete.message.success': 'Successfully delete this land...',

                    'tip': '§eYou are now on the land: §f{0} §eowned by §f{1}',
                    'message.on_block_break': 'You cannot break blocks on this land...',
                    'message.on_player_attack': 'You cannot attack players or mobs on this land...',
                    'message.on_player_right_click_block': 'You cannot right-click on blocks on this land...',
                    'message.on_player_right_click_entity': 'You cannot right-click on entities on this land...'
                }
                json_str = json.dumps(en_US, indent=4, ensure_ascii=False)
                f.write(json_str)

        lang_data = {}
        lang_list = os.listdir(lang_dir)
        for lang in lang_list:
            lang_name = lang.strip('.json')
            lang_data_file_path = os.path.join(lang_dir, lang)
            with open(lang_data_file_path, 'r', encoding='utf-8') as f:
                lang_data[lang_name] = json.loads(f.read())

        return lang_data
